Working textures
BykadorovR/UnlimitedEnginePro pull request #2
Opened 2017-07-15 21:28 UTC by jenia-aka-nels

2017-07-16 05:58 UTC, BykadorovR commented
Please add changes related to Devil to travis.yml and be sure that build is successful.

2017-07-16 06:16 UTC, BykadorovR requested changes

2017-07-16 06:16 UTC, BykadorovR commented on engine/content/simple.fs
> +    FragColor = texture2D(gSampler, TexCoord0.xy);
TexCoord is vec2, why do you use TexCoord0.xy instead of TexCoord0?

2017-07-16 06:16 UTC, BykadorovR commented on engine/graphic/include/Texture.h
> +	Texture(char* FileName);
Let's use string instead of char*
std::string text
If you want to get char* from string, just write text.c_str()

2017-07-16 06:16 UTC, BykadorovR commented on engine/graphic/include/Texture.h
> +	char* m_fileName;
the same as above

2017-07-16 06:16 UTC, BykadorovR commented on engine/graphic/src/Texture.cpp
> +	// ������ ����������� �������
Please use English for comments

2017-07-16 06:16 UTC, BykadorovR commented on engine/graphic/src/Texture.cpp
> +	imageId = 0;
Maybe it will be better to set ID for texture manually?
In case of a lot of texture atlases it will be very convenient

2017-07-16 06:16 UTC, BykadorovR commented on engine/graphic/src/Texture.cpp
> +		case 24:
Do we really need to handle RGB case?

2017-07-16 06:16 UTC, BykadorovR commented on engine/graphic/src/Texture.cpp
> +		ilBindImage(0);
Also add some id to this function

2017-07-16 09:09 UTC, jenia-aka-nels commented
image is in "app" folder, I could make another folder like "resources" inside

2017-07-16 09:19 UTC, jenia-aka-nels commented on engine/graphic/src/Texture.cpp
> +		ilBindImage(0);
this is an unbind function

2017-07-16 13:46 UTC, jenia-aka-nels commented
DONE!! DO NOT look at sprites for now!

2017-07-17 06:53 UTC, BykadorovR commented
If your work on sprite isn't ended, please remove these changes from pull request (it's good practice, push only changes that are fully done)
You can do: 
git reset --soft <commit' sha>
It will mark all files which were added by this commit as "uncommitted" so you can split a lot of commits to 2, for example. The first commit will contain only changes that aren't related to Sprite and you can create pull request on it's basis and the second will contain all other changes.
Also please write some notes or fix rest of my comments. Thanks :)

2017-07-17 07:38 UTC, jenia-aka-nels commented on engine/graphic/src/Texture.cpp
> +		case 24:
hz

2017-07-17 07:42 UTC, jenia-aka-nels commented on engine/graphic/src/Texture.cpp
> +	imageId = 0;
We will be working with Texture* so I don't see any use for IDs.

2017-07-17 07:50 UTC, BykadorovR commented on engine/graphic/src/Texture.cpp
> +	imageId = 0;
But as I described to you, there is possibility to bind texture to specific execution unit. Now we have some magic numbers in code :)

2017-07-17 07:50 UTC, BykadorovR commented on engine/graphic/src/Texture.cpp
> +		case 24:
Will you draw images without alpha channel?

2017-07-17 07:52 UTC, jenia-aka-nels commented on engine/graphic/src/Texture.cpp
> +	imageId = 0;
I don't see any magic numbers, ImageId is being set here:
13	ilGenImages(1, &imageId);

2017-07-17 07:53 UTC, BykadorovR commented on engine/graphic/src/Texture.cpp
> +	imageId = 0;
What does first argument mean and why it is equal to 1?

2017-07-17 07:54 UTC, jenia-aka-nels commented on engine/graphic/src/Texture.cpp
> +		case 24:
may be

2017-07-17 07:54 UTC, BykadorovR commented on engine/graphic/src/Texture.cpp
> +	imageId = 0;
Why imageId equal to zero and there is no possibility to set it to 1,2,3,4? And what is difference between these options?

2017-07-17 07:54 UTC, jenia-aka-nels commented on engine/graphic/src/Texture.cpp
> +	imageId = 0;
ilGenImages(1 - number of images

2017-07-17 07:55 UTC, BykadorovR commented on engine/graphic/src/Texture.cpp
> +	imageId = 0;
Ok, I see
What about imageId = 0?

2017-07-17 07:56 UTC, BykadorovR commented on engine/graphic/src/Texture.cpp
> +		ilBindImage(0);
But you use index "0"

2017-07-17 07:57 UTC, BykadorovR commented on engine/graphic/src/Texture.cpp
> +	imageId = 0;
Ok, it will be initialized later

2017-07-17 07:57 UTC, jenia-aka-nels commented on engine/graphic/src/Texture.cpp
> +	imageId = 0;
ImageId is being set this way:
13 ilGenImages(1, &imageId);
value before it doesent matter, its just an initialization

2017-07-17 08:00 UTC, jenia-aka-nels commented on engine/graphic/src/Texture.cpp
> +		ilBindImage(0);
do I need to define 0 as THE_UNBINDING_IMAGE_ID ?

2017-07-17 08:01 UTC, BykadorovR commented on engine/graphic/src/Texture.cpp
> +		ilBindImage(0);
I just try to understand, how we can bind texture to specific execution unit/texture buffer, because now in your impl I don't see this possibility

2017-07-17 08:03 UTC, jenia-aka-nels commented on engine/graphic/src/Texture.cpp
> +		ilBindImage(0);
ilBindImage is a DevIL function for loading images, not an OpenGL func

2017-07-17 08:03 UTC, BykadorovR commented on engine/graphic/src/Texture.cpp
> +		ilBindImage(0);
It's not GL function, though. So I really can't understand how I can bind atlases to different buffers

2017-07-17 08:06 UTC, BykadorovR commented on engine/graphic/src/Texture.cpp
> +		ilBindImage(0);
I think glActiveTexture(GL_TEXTURE0); can do it

2017-07-17 08:13 UTC, BykadorovR commented on engine/graphic/src/Texture.cpp
> +		ilBindImage(0);
Please see https://github.com/BykadorovR/TimeOfWitch/blob/master/src/com/timeOfWitch/android/util/TextureHelper.java

2017-07-17 09:35 UTC, BykadorovR commented on engine/graphic/src/Texture.cpp
> +	else return false;
You can just write "return false" without else

2017-07-17 12:37 UTC, BykadorovR approved these changes

2017-07-23 11:46 UTC, BykadorovR commented
Please split pull requests to separates part, because it very hard to review so big amount of commits

2017-08-14 19:05 UTC, BykadorovR commented
Unfortunately, for now it is impossible to review these tons of code and make notes.
My suggestion is splitting this pull request to separate ones (one commit - one pull request). It's very simple to do it, just create separate branches for every commit (i.e. git checkout to first commit, git branch -b commit1, git push origin HEAD:commit1 and after create pull request from this commit or make git push upstream HEAD:dev without additional pull requests but if upstream is configured)

2017-08-14 19:05 UTC, closed without merging